config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  devise_for :users
  resources :products do
    member do
      post :edit
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/views/shared/_flash_notice.html.erb
    <% flash.each do |type, message| %>
      <div data-controller="flash" class="flex items-center fixed top-5 right-5 <%= flash_classes(type) %> py-3 px-5 rounded-lg">
        <div class="mr-4"><%= message %></div>

        <button type="button" data-action="flash#dismiss">
          <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    <% end %>

app/views/shared/_footer.html.erb
<div class="mt-6">
  <a href="https://www.buymeacoffee.com/jesusalc" target="_blank"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&amp;emoji=&amp;slug=jesusalc&amp;button_colour=f0f0f0&amp;font_colour=333333&amp;font_family=Cookie&amp;outline_colour=333333&amp;coffee_colour=555555"></a>
</div>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Probeausgabe7turbo" %>
  </title>
   <meta charset="utf-8">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!--  <meta name="viewport" content="width=device-width, initial-scale=1">-->
  <%= javascript_include_tag "application", defer: true %>

   <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

   <%= javascript_importmap_tags %>
   <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbo-track': 'reload' %>

   <style>
       #menu-toggle:checked + #menu {
           display: block;
       }
   </style>
</head>

app/views/shared/_navbar.html.erb
<div class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto lg:px-0 px-4 <%= nav_classes %>" data-controller="nav">
  <div class="flex-1 flex justify-between items-center">
    <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only"><%= content_for?(:title) ? yield(:title) : "Probeausgabe7turbo" %></span>
      <%# Remove this logo and add your own  https://www.softr.io/tools/svg-shape-generator %>
      <%# <svg width="100" height="100" id="sw-js-blob-svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">                    <defs>                         <linearGradient id="sw-gradient" x1="0" x2="1" y1="1" y2="0">                            <stop id="stop1" stop-color="rgba(160.172, 106.427, 80.99, 1)" offset="0%"></stop>                            <stop id="stop2" stop-color="rgba(228.475, 159.581, 45.863, 1)" offset="100%"></stop>                        </linearGradient>                    </defs>                <path fill="url(#sw-gradient)" d="M6.2,-13.2C7.8,-9.8,8.6,-7.6,10.4,-5.6C12.3,-3.6,15.1,-1.8,15.9,0.4C16.6,2.7,15.2,5.3,12.2,5.4C9.3,5.4,4.7,2.8,2.4,8.8C0.1,14.8,0,29.5,-0.5,30.4C-1,31.2,-2.1,18.3,-3.7,11.9C-5.3,5.4,-7.5,5.5,-13.5,4.6C-19.6,3.7,-29.4,1.9,-29.7,-0.1C-29.9,-2.1,-20.4,-4.2,-14.2,-4.9C-8.1,-5.6,-5.3,-4.9,-3.5,-8.2C-1.6,-11.5,-0.8,-18.7,0.7,-20C2.3,-21.3,4.6,-16.6,6.2,-13.2Z" width="100%" height="100%" transform="translate(50 50)" style="transition: all 0.3s ease 0s;" stroke-width="0" stroke="url(#sw-gradient)"></path>              </svg>%>
      <svg width="50" height="50" id="sw-js-blob-svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">                    <defs>                         <linearGradient id="sw-gradient" x1="0" x2="1" y1="1" y2="0">                            <stop id="stop1" stop-color="rgba(203.431, 132.831, 99.418, 1)" offset="0%"></stop>                            <stop id="stop2" stop-color="rgba(27.802, 85.704, 228.475, 1)" offset="100%"></stop>                        </linearGradient>                    </defs>                <path fill="url(#sw-gradient)" d="M9.9,-22.2C11.6,-16.2,10.9,-11,16.9,-7.5C23,-3.9,35.8,-2,36.2,0.2C36.6,2.4,24.7,4.9,20.5,11.8C16.4,18.6,20.1,30,18,31.9C15.9,33.9,7.9,26.5,1.2,24.5C-5.6,22.5,-11.3,25.9,-17.2,26.2C-23.2,26.4,-29.5,23.6,-32.2,18.7C-34.9,13.8,-33.9,6.9,-29.7,2.4C-25.4,-2,-17.9,-4,-13.4,-5.8C-9,-7.5,-7.5,-9,-5.8,-14.9C-4,-20.8,-2,-31.1,1.1,-32.9C4.1,-34.7,8.2,-28.1,9.9,-22.2Z" width="100%" height="100%" transform="translate(50 50)" style="transition: all 0.3s ease 0s;" stroke-width="0" stroke="url(#sw-gradient)"></path>              </svg>
    <% end %>
  </div>

  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button  class="hidden flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" id="menu-toggle"  data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
    <label for="menu-toggle" class="pointer-cursor lg:hidden block">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </label>
  </div>


  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden hidden lg:flex lg:items-center lg:w-auto w-full" id="menu" data-nav-target="menu">
    <nav  class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <% if user_signed_in? %>
      <ul class="lg:flex items-center justify-between text-base text-gray-700 pt-4 lg:pt-0">
        <% if Socket.gethostname == ENV['DEVELOPER_HOSTNAME'] %>
        <li>
          <%= link_to "Routes " + Time.zone.now.to_s, '/rails/info/routes', class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
        </li>
        <% end %>
        <li>
            <%= link_to "About", home_about_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
        </li>
        <li>
            <%= link_to "Products", products_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
        </li>
      </ul>
      <% end %>
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to "Edit account", edit_user_registration_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2 lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/jesusalc/rails_7_tailwind_navbar_devise_products_shopify", target: :_blank, class: "group lg:ml-2 flex justify-center lg:p-4 py-3 px-0 block border-b-2 border-transparent hover:border-indigo-400" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </nav>

  </div>
</div>